### ISSUE TITLE
MongoDBDriver issue

### ISSUE THREAD

**Issue by omar00050** [good-db/good.db#1]
When using the nested option, it does not fetch the data correctly and returns an error stating that it cannot read the value, and then
TypeError: Cannot read properties of null

He was referring to a file
\good.db\dist\utils\nested.js:44:27)

When this function getValueAtPath checked the object, it returned an undefined object, but it was not checking the object. Rather, it was checking whether it was an object or something else, and this is an error.

```js
function setValueAtPath(object, key, value, options) {
    const { separator = '..' } = options || {};
    const keyParts = key.split(separator);
    let currentObject = object;

    if (typeof object !== 'object' ) {
         return undefined;
    }

    for (let i = 0; i < keyParts.length - 1; i++) {
        const part = keyParts[i];
        if (!currentObject[part]) {
            currentObject[part] = {};
        }
        else if (typeof currentObject[part] !== 'object') {
            throw new ErrorMessage_1.DatabaseError(`Cannot create property '${part}' on ${typeof currentObject[part]}`);
        }
        currentObject = currentObject[part];
    }
    ;
    const lastPart = keyParts[keyParts.length - 1];
    const isArrayIndex = !isNaN(parseInt(lastPart, 10));
    if (Array.isArray(currentObject) && !isArrayIndex) {
        throw new ErrorMessage_1.DatabaseError(`Cannot set value at '${key}' because '${lastPart}' is not a valid array index.`);
    }
    ;
    currentObject[lastPart] = value;
    return {
        object,
        key: keyParts[0],
        value,
        currentObject: object[keyParts[0]]
    };
}
```

# This error is present in two functions getValueAtPath and setValueAtPath, and then you can modify them.

## before
```js
    if (typeof object !== 'object' ) {
        return undefined;
    }
```

## after

```js
    if (typeof object !== 'object' || !object) {
        // return undefined;
        return {
            object,
            key: keyParts[keyParts.length - 1],
            value: undefined,
            currentObject: undefined
        }
    }
```
But there are also some problems. Please fix them quickly because it does not capture the object correctly 
Thanks...

**Comment by usifme** [comment]
Thanks for your update, @omar00050! I see now that the issue stemmed from the setting system, specifically in the ASYNC function, which caused undefined data due to the key not being properly set beforehand or the value being undefined without replacement to an object.

I took a look at the commit you provided, and it seems like a step in the right direction to address this issue. Your effort is greatly appreciated in identifying and suggesting a fix for the problem.

It's important to clarify that while Omar didn't directly implement the update, his report and suggestion were instrumental in identifying and resolving the issue. This demonstrates the collaborative nature of open-source projects, where community feedback and contributions are essential for improvement.

Once again, thank you for your contribution, Omar! Your involvement helps ensure the reliability and functionality of the package for its users. You can check out the new update [here](https://github.com/good-db/good.db/commit/d1acc2d9399a0adbead6628fa67747279eb9ee25#diff-2caefbbf7d8e7ac45dfc26000cd726c8275bd43cf705af449aa0535b3a5f7631).
